import { mylenis } from './module/lenis';
import { Gsap } from './module/gsap';
import { Scroll } from './module/scroll';
import { anime } from './module/anime';
import { Animation } from './module/animation';
import { Effects } from './module/effects';
import { Accordion } from './module/accordion';
import { Menu } from './module/menu';
import { HeaderScroll } from './module/headerscroll';
import { Stripe } from './module/stripeline';
import { Browse } from './module/browse';
import { sticky } from './module/stickmeterial';
import { Blockquote } from './module/blockquote';
import { Video } from './module/video';
import { jslineanimation } from './module/js-line-animation';
import { support } from './module/support';
import { Stickyfeatures } from './module/careerstickyfeature';
import { innovation } from './module/innovation';
import { slider } from './module/slider';
import { magnificPopup } from './module/magnificpopup';
import { usecases } from './module/usecases';
import { usecasesbr } from './module/usecasepage';
import { counter } from './module/counter';
import { myslick } from './module/slick';
import { aislick } from './module/aiSlick';
import { usecase } from './module/casetwo';
import { poweredobj } from './module/poweredby';
import { prodslick } from './module/prodCompareSlick';
import { automated } from './module/automated';
import { lifeatslider } from './module/lifeatslider';
import { sidebar } from './module/sidebarsticky';
import { software } from './module/product-software';
import { usesticky } from './module/useIntroSticky';
import { convas } from './module/convas';
import { featuredIcon } from './module/featuredIconSticky';
import { solstatsgraphs } from './module/solutionPage';
import { trustbrandSlider } from './module/trustbrandSlider';
import { coountSolLI } from './module/countLi';
import { coountProdLI } from './module/countProdLi';

document.addEventListener('DOMContentLoaded', function () {
  mylenis.init();
  Gsap.init();
  anime.init();
  Animation.init();
  Effects.init();
  Accordion.init();
  Menu.init();
  HeaderScroll.init();
  Stripe.init();
  Browse.init();
  Blockquote.init();
  Video.init();
  jslineanimation.init();
  support.init();
  innovation.init();
  slider.init();
  magnificPopup.init();
  usecases.init();
  counter.init();
  myslick.init();
  usecase.init();
  usecasesbr.init();
  aislick.init();
  poweredobj.init();
  prodslick.init();
  automated.init();
  lifeatslider.init();
  software.init();
  convas.init();
  solstatsgraphs.init();
  coountSolLI.list();
  coountProdLI.prodlist();
  trustbrandSlider.init();
});
document.addEventListener('DOMContentLoaded', function () {
  let scrolled = window.scrollY;
  window.addEventListener('scroll', function () {
    scrolled = window.scrollY;
    Scroll.handle(scrolled);
    Animation.handle(scrolled, Scroll.direction);
  });
  Scroll.handle(scrolled);
  Animation.handle(scrolled, Scroll.direction);
});

window.addEventListener('load', function () {
  sticky.init();
  usesticky.init();
  Stickyfeatures.init();
  sidebar.init();
  featuredIcon.init();
});
