import { mylenis } from './module/lenis';
import { Gsap } from './module/gsap';
import { Scroll } from './module/scroll';
import { anime } from './module/anime';
import { Animation } from './module/animation';
import { Effects } from './module/effects';
import { Accordion } from './module/accordion';
import { Menu } from './module/menu';
import { HeaderScroll } from './module/headerscroll';
import { Stripe } from './module/stripeline';
import { Browse } from './module/browse';
import { sticky } from './module/stickmeterial';
import { Blockquote } from './module/blockquote';
import { Video } from './module/video';
import { jslineanimation } from './module/js-line-animation';
import { support } from './module/support';
import { Stickyfeature } from './module/careerstickyfeature';
import { innovation } from './module/innovation';
import { slider } from './module/slider';
import { magnificPopup } from './module/magnificpopup';
import { usecases } from './module/usecases';
import { usecasesbr } from './module/usecasepage';
import { counter } from './module/counter';
import { myslick } from './module/slick';
import { aislick } from './module/aiSlick';
import { usecase } from './module/casetwo';
import { poweredobj } from './module/poweredby';
import { prodslick } from './module/prodCompareSlick';
import { automated } from './module/automated';
import { lifeatslider } from './module/lifeatslider';

document.addEventListener('DOMContentLoaded', function () {
  mylenis.init();
  Gsap.init();
  anime.init();
  Animation.init();
  Effects.init();
  Accordion.init();
  Menu.init();
  HeaderScroll.init();
  Stripe.init();
  Browse.init();
  sticky.init();
  Blockquote.init();
  Video.init();
  jslineanimation.init();
  support.init();
  Stickyfeature.init();
  innovation.init();
  slider.init();
  magnificPopup.init();
  usecases.init();
  counter.init();
  myslick.init();
  usecase.init();
  usecasesbr.init();
  aislick.init();
  poweredobj.init();
  prodslick.init();
  automated.init();
  lifeatslider.init();
});

let scrolled = window.scrollY;
window.addEventListener('scroll', function () {
  scrolled = window.scrollY;
  Scroll.handle(scrolled);
  Animation.handle(scrolled, Scroll.direction);
});
